build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-golang-1.12
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: hello
  commands: echo hello
  container:
    from: src
- as: plugin-test
  commands: echo "testing in-repo-config plugin"
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: Prucek
  repo: ci-staging
