build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-golang-1.12
releases:
  latest:
    release:
      channel: stable
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: hello
  cluster: build09
  commands: echo "hello from ci-staging v2!" && date && uname -a
  container:
    from: src
- as: e2e-aws
  cluster: build09
  steps:
    cluster_profile: aws
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: Prucek
  repo: ci-staging
- as: simple-test
  cluster: build09
  commands: echo "simple test added for mount verification"
  container:
    from: src
